name: 'deel_analytics'
version: '1.0'
require-dbt-version: ">=1.3.0"
config-version: 2

profile: 'default'

# Source paths
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  deel_analytics:
      silver_layer:
        database: silver_layer
        operations:
          schema: operations
          materialized: incremental
          incremental_strategy: merge
          on_schema_change: sync_all_columns
      preparation:
        database: preparation
        materialized: view
        operations:
          schema: operations
      marts:
        database: marts
        schema: main
        materialized: table

